### ISSUE TITLE
这个项目太牛逼了

### ISSUE THREAD

**Issue by liuruoze** [Uahh/slscq#10]
别的项目我都没事不会发issue留言，面对这个项目我情不自禁的起了一个issue写了这段无意义的话。

**Comment by Uahh** [comment]
草，谢谢

> 别的项目我都没事不会发issue留言，面对这个项目我情不自禁的起了一个issue写了这段无意义的话。

**Comment by LUERUI** [comment]
想问问文章生成的原理是什么？

**Comment by tgwl** [comment]
> 想问问文章生成的原理是什么？

看代码，其实就是循环替换指定文字。
