### ISSUE TITLE
建议降低文章字句的重复率

### ISSUE THREAD

**Issue by LittleYe233** [Uahh/slscq#11]
多次测试之后发现，生成的文章存在较大量的对文章标题的重复，在文章标题存在破折号等标点符号时尤为显眼。建议通过一些方法降低文章字句的重复程度，例如：文章标题重组、增设近义词词库等。

**Comment by Dimlitter** [comment]
是的 希望好好改进
>（以后形策课的作文全靠它了）

**Comment by Uahh** [comment]
这个项目是写着玩的..肯定达不到能使用的要求，您看一下data.json那个文件就明白了> 多次测试之后发现，生成的文章存在较大量的对文章标题的重复，在文章标题存在破折号等标点符号时尤为显眼。建议通过一些方法降低文章字句的重复程度，例如：文章标题重组、增设近义词词库等。
